2023-11-25 18:41:04,761 INFO n = 7
2023-11-25 18:41:04,762 INFO suitable
2023-11-25 18:41:06,841 INFO k = 3
2023-11-25 18:41:06,841 INFO hidden_num = 5
2023-11-25 18:41:09,059 INFO input num = 3
2023-11-25 18:41:09,059 INFO suitable
2023-11-25 18:41:09,059 INFO the number isn't guessed
2023-11-25 18:41:14,071 INFO input num = 1
2023-11-25 18:41:14,071 INFO suitable
2023-11-25 18:41:14,072 INFO the number isn't guessed
2023-11-25 18:41:15,479 INFO input num = 2
2023-11-25 18:41:15,479 INFO suitable
2023-11-25 18:41:15,479 INFO the number isn't guessed
2023-11-25 18:41:15,480 INFO attempts ended
2023-11-25 18:41:47,569 INFO n = 10
2023-11-25 18:41:47,569 INFO suitable
2023-11-25 18:41:49,178 INFO k = 5
2023-11-25 18:41:49,178 INFO hidden_num = 4
2023-11-25 18:41:52,784 INFO input num = 12
2023-11-25 18:41:52,784 ERROR not in range
Traceback (most recent call last):
  File "d:\labz9\main.py", line 49, in <module>
    assert 1 <= num <= n
AssertionError
2023-11-25 18:41:56,297 INFO input num = 4
2023-11-25 18:41:56,297 INFO suitable
2023-11-25 18:41:56,298 INFO the number is guessed
